apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: mystoremicroservices-orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__OrderConnection
              value: "Host=orderservice-postgres;Port=5432;Database=OrderDb;Username=postgres;Password=postgres"
            - name: Services__ProductService
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_SERVICE_URL

            - name: RabbitMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST

            - name: RabbitMQ__Port
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT
            - name: RabbitMQ__Username
              value: "guest"
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD